terraform: fix aws-vpc module to version "~> v1.0"
```
The `storage` parameter is deprecated. Please migrate to using built-in Terraform backends as described here: https://github.com/ljfranklin/terraform-resource#backend-migration.

2019/06/17 16:35:58 terraform init command failed.
Error: exit status 1
Output: Initializing modules...
- module.infrastructure
  Getting source "module-infrastructure"
- module.infrastructure.infra_vpc
  Found version 2.7.0 of terraform-aws-modules/vpc/aws on registry.terraform.io
  Getting source "terraform-aws-modules/vpc/aws"
Error downloading modules: Error loading modules: module infra_vpc: Error parsing .terraform/modules/c7754049851005d71d05529bacf9d67e/terraform-aws-modules-terraform-aws-vpc-271b6a7/main.tf: At 2:23: Unknown token: 2:23 IDENT max
```

https://cycloid-io.slack.com/archives/C09LPKN21/p1560765414171900