terraform: remove admin-users that can't be determined correctly during a terraform plan
Error:
```
Error: Invalid count argument
  on module-infrastructure/account_iam.tf line 25, in resource "aws_iam_user_policy_attachment" "infra_administrator_access_user":
  25:   count      = length(local.admin-users)

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```